In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt
from scipy import stats
pd.set_option('display.max_rows', 200) #number of rows for printing

In [ ]:
from google.colab import files
uploaded = files.upload()       #upload the file to google colab
import io
data = pd.read_excel(io.BytesIO(uploaded['Location.xlsx']))      #read the uploaded excel file
data

Saving Location.xlsx to Location (5).xlsx


Eva_1     Evb_1     Evc_1  ...     Evc_2  Location         class
0   0.080313  0.343100  0.576587  ...  0.501805         4  BC_nonground
1   0.446246  0.037825  0.515929  ...  0.498285         4  AC_nonground
2   0.605344  0.196966  0.197691  ...  0.003290         4            AG
3   0.983248  0.008130  0.008622  ...  0.197269         3            AG
4   0.949568  0.006566  0.043865  ...  0.400750         3            AC
5   0.189513  0.205092  0.605395  ...  0.991536         4            CG
6   0.181234  0.633001  0.185765  ...  0.188205         2            BG
7   0.651789  0.052713  0.295499  ...  0.339456         2            AC
8   0.056972  0.404159  0.538869  ...  0.507470         2  BC_nonground
9   0.191552  0.203290  0.605158  ...  0.991940         4            CG
10  0.497424  0.488002  0.014574  ...  0.005194         2  AB_nonground
11  0.638575  0.180548  0.180878  ...  0.184411         2            AG
12  0.486334  0.006801  0.506865  ...  0.499904         2  AC_nonground
13  0.448882  0.489593  0.061525  ...  0.000355         4  AB_nonground
14  0.193417  0.201792  0.604791  ...  0.992273         4            CG
15  0.180895  0.184452  0.634653  ...  0.632267         2            CG
16  0.008214  0.984105  0.007681  ...  0.197640         3            BG
17  0.441515  0.451381  0.107104  ...  0.006099         4            AB
18  0.196452  0.605914  0.197634  ...  0.002604         4            BG
19  0.195883  0.605960  0.198157  ...  0.002389         4            BG
20  0.180070  0.637247  0.182682  ...  0.186030         2            BG
21  0.003840  0.493117  0.503044  ...  0.513800         3  BC_nonground
22  0.179515  0.180817  0.639667  ...  0.632386         2            CG
23  0.501547  0.000816  0.497637  ...  0.506057         3  AC_nonground
24  0.632636  0.183226  0.184138  ...  0.185577         2            AG
25  0.181382  0.630081  0.188537  ...  0.190935         2            BG
26  0.008980  0.009635  0.981385  ...  0.605419         3            CG
27  0.496941  0.501723  0.001336  ...  0.016595         3  AB_nonground
28  0.008370  0.983715  0.007915  ...  0.197460         3            BG
29  0.605440  0.197091  0.197469  ...  0.003257         4            AG
30  0.983755  0.007781  0.008464  ...  0.197441         3            AG
31  0.187863  0.341135  0.471003  ...  0.072186         4            BC
32  0.625453  0.368836  0.005711  ...  0.121748         3            AB
33  0.321068  0.574490  0.104442  ...  0.252240         2            BC
34  0.008938  0.009758  0.981304  ...  0.605895         3            CG
35  0.180719  0.182974  0.636307  ...  0.631966         2            CG
36  0.605485  0.196989  0.197526  ...  0.003262         4            AG
37  0.014673  0.894433  0.090894  ...  0.395372         3            BC
38  0.196144  0.606026  0.197829  ...  0.002484         4            BG
39  0.008954  0.009952  0.981093  ...  0.606217         3            CG
40  0.500512  0.168627  0.330860  ...  0.032735         4            AC
41  0.008113  0.984384  0.007503  ...  0.197968         3            BG
42  0.983557  0.007927  0.008515  ...  0.197295         3            AG
43  0.555375  0.417693  0.026932  ...  0.074742         2            AB
44  0.634837  0.182294  0.182869  ...  0.185067         2            AG

[45 rows x 8 columns]

In [ ]:
#random.shuffle(data)
#data
#data = data.sample(frac=1).reset_index(drop=True)
#data.to_excel('shuffled.xlsx')

data = data.drop(columns=['class'])            

data

Eva_1     Evb_1     Evc_1     Eva_2     Evb_2     Evc_2  Location
0   0.080313  0.343100  0.576587  0.000778  0.497417  0.501805         4
1   0.446246  0.037825  0.515929  0.501514  0.000202  0.498285         4
2   0.605344  0.196966  0.197691  0.994117  0.002594  0.003290         4
3   0.983248  0.008130  0.008622  0.605838  0.196892  0.197269         3
4   0.949568  0.006566  0.043865  0.478637  0.120613  0.400750         3
5   0.189513  0.205092  0.605395  0.003696  0.004768  0.991536         4
6   0.181234  0.633001  0.185765  0.183194  0.628601  0.188205         2
7   0.651789  0.052713  0.295499  0.566736  0.093809  0.339456         2
8   0.056972  0.404159  0.538869  0.022908  0.469622  0.507470         2
9   0.191552  0.203290  0.605158  0.003592  0.004467  0.991940         4
10  0.497424  0.488002  0.014574  0.496697  0.498109  0.005194         2
11  0.638575  0.180548  0.180878  0.631501  0.184088  0.184411         2
12  0.486334  0.006801  0.506865  0.497869  0.002227  0.499904         2
13  0.448882  0.489593  0.061525  0.498100  0.501545  0.000355         4
14  0.193417  0.201792  0.604791  0.003516  0.004211  0.992273         4
15  0.180895  0.184452  0.634653  0.181963  0.185770  0.632267         2
16  0.008214  0.984105  0.007681  0.195989  0.606371  0.197640         3
17  0.441515  0.451381  0.107104  0.610691  0.383210  0.006099         4
18  0.196452  0.605914  0.197634  0.003065  0.994331  0.002604         4
19  0.195883  0.605960  0.198157  0.003010  0.994601  0.002389         4
20  0.180070  0.637247  0.182682  0.183610  0.630360  0.186030         2
21  0.003840  0.493117  0.503044  0.039577  0.446623  0.513800         3
22  0.179515  0.180817  0.639667  0.183282  0.184332  0.632386         2
23  0.501547  0.000816  0.497637  0.485216  0.008727  0.506057         3
24  0.632636  0.183226  0.184138  0.630037  0.184385  0.185577         2
25  0.181382  0.630081  0.188537  0.182148  0.626917  0.190935         2
26  0.008980  0.009635  0.981385  0.194473  0.200108  0.605419         3
27  0.496941  0.501723  0.001336  0.493881  0.489524  0.016595         3
28  0.008370  0.983715  0.007915  0.196303  0.606237  0.197460         3
29  0.605440  0.197091  0.197469  0.993986  0.002757  0.003257         4
30  0.983755  0.007781  0.008464  0.605843  0.196716  0.197441         3
31  0.187863  0.341135  0.471003  0.007617  0.920197  0.072186         4
32  0.625453  0.368836  0.005711  0.466081  0.412170  0.121748         3
33  0.321068  0.574490  0.104442  0.352628  0.395131  0.252240         2
34  0.008938  0.009758  0.981304  0.193090  0.201015  0.605895         3
35  0.180719  0.182974  0.636307  0.182931  0.185103  0.631966         2
36  0.605485  0.196989  0.197526  0.994074  0.002664  0.003262         4
37  0.014673  0.894433  0.090894  0.263047  0.341581  0.395372         3
38  0.196144  0.606026  0.197829  0.003027  0.994489  0.002484         4
39  0.008954  0.009952  0.981093  0.191609  0.202174  0.606217         3
40  0.500512  0.168627  0.330860  0.963129  0.004136  0.032735         4
41  0.008113  0.984384  0.007503  0.195739  0.606293  0.197968         3
42  0.983557  0.007927  0.008515  0.605948  0.196758  0.197295         3
43  0.555375  0.417693  0.026932  0.512407  0.412851  0.074742         2
44  0.634837  0.182294  0.182869  0.630541  0.184392  0.185067         2

In [ ]:
x_df = data.iloc[:,:6]       #specifiy the input
y_df = data.iloc[:,6]        #specifiy the target

In [ ]:
from sklearn.preprocessing import scale, minmax_scale
x_df=scale(x_df)                #standardize the data

In [ ]:
x_df=pd.DataFrame(x_df)                 #change the data to a dataframe
x_df

0         1         2         3         4         5
0  -0.968126  0.029566  0.965660 -1.233808  0.569349  0.699150
1   0.294770 -1.041126  0.750382  0.482482 -1.158051  0.686597
2   0.843843 -0.482972 -0.379054  2.170895 -1.149740 -1.078302
3   2.148054 -1.145277 -1.050062  0.840057 -0.474718 -0.386669
4   2.031820 -1.150760 -0.924984  0.404070 -0.739722  0.338836
5  -0.591256 -0.454471  1.067899 -1.223807 -1.142187  2.445279
6  -0.619831  1.046337 -0.421377 -0.608571  1.025103 -0.418989
7   1.004133 -0.988911 -0.031931  0.706032 -0.832846  0.120294
8  -1.048678  0.243717  0.831798 -1.157957  0.472784  0.719349
9  -0.584221 -0.460789  1.067056 -1.224162 -1.143231  2.446720
10  0.471395  0.537781 -1.028940  0.465973  0.571752 -1.071511
11  0.958529 -0.540554 -0.438724  0.928017 -0.519202 -0.432515
12  0.433120 -1.149938  0.718215  0.469990 -1.151015  0.692370
13  0.303868  0.543362 -0.862309  0.470781  0.583689 -1.088764
14 -0.577785 -0.466045  1.065757 -1.224424 -1.144121  2.447906
15 -0.620999 -0.526862  1.171737 -0.612790 -0.513360  1.164310
16 -1.216951  2.277767 -1.053404 -0.564716  0.947872 -0.385349
17  0.278444  0.409339 -0.700548  0.856691  0.172577 -1.068286
18 -0.567311  0.951335 -0.379254 -1.225968  2.295702 -1.080747
19 -0.569275  0.951496 -0.377398 -1.226156  2.296639 -1.081514
20 -0.623847  1.061231 -0.432318 -0.607146  1.031214 -0.426743
21 -1.232048  0.555721  0.704651 -1.100821  0.392882  0.741916
22 -0.625762 -0.539609  1.189533 -0.608269 -0.518355  1.164733
23  0.485624 -1.170927  0.685462  0.426620 -1.128431  0.714308
24  0.938033 -0.531159 -0.427154  0.923000 -0.518169 -0.428357
25 -0.619318  1.036094 -0.411540 -0.612156  1.019253 -0.409255
26 -1.214309 -1.139996  2.402297 -0.569911 -0.463546  1.068582
27  0.469729  0.585903 -1.075921  0.456320  0.541928 -1.030862
28 -1.216413  2.276397 -1.052571 -0.563641  0.947408 -0.385990
29  0.844174 -0.482531 -0.379840  2.170448 -1.149173 -1.078419
30  2.149804 -1.146501 -1.050622  0.840072 -0.475330 -0.386057
31 -0.596954  0.022673  0.590938 -1.210368  2.038151 -0.832653
32  0.913244  0.119831 -1.060395  0.361035  0.273190 -0.655939
33 -0.137241  0.841122 -0.709994 -0.027829  0.213993 -0.190671
34 -1.214452 -1.139565  2.402009 -0.574653 -0.460394  1.070280
35 -0.621607 -0.532045  1.177607 -0.609471 -0.515676  1.163235
36  0.844331 -0.482890 -0.379637  2.170750 -1.149496 -1.078402
37 -1.194659  1.963260 -0.758080 -0.334871  0.027952  0.319662
38 -0.568372  0.951728 -0.378561 -1.226100  2.296251 -1.081174
39 -1.214396 -1.138884  2.401261 -0.579726 -0.456370  1.071428
40  0.482053 -0.582363  0.093568  2.064683 -1.144381 -0.973315
41 -1.217299  2.278744 -1.054035 -0.565573  0.947600 -0.384178
42  2.149121 -1.145986 -1.050442  0.840433 -0.475186 -0.386579
43  0.671392  0.291186 -0.985079  0.519819  0.275554 -0.823539
44  0.945629 -0.534429 -0.431657  0.924725 -0.518145 -0.430177

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier              #we want to try learning through KNN
from sklearn.model_selection import train_test_split  
x_train,x_test,y_train,y_test=train_test_split(x_df,y_df,test_size=0.2,random_state=42)      #split the data to training and testing set



knn=KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)                   #first set these parameters and check the performance, we will later fine tune the parameters
knn=knn.fit(x_train,y_train)                       #fit the model to our train data
y_pred = knn.predict(x_test)

In [ ]:
pd.set_option('display.max_rows', 100) #number of rows for printing
print(y_train)

3     3
6     2
24    2
32    3
19    4
17    4
13    4
42    3
15    2
9     4
16    3
37    3
31    4
27    3
0     4
30    3
29    4
5     4
11    2
33    2
1     4
40    4
21    3
2     4
34    3
23    3
36    4
10    2
22    2
18    4
44    2
20    2
7     2
14    4
28    3
38    4
Name: Location, dtype: int64


In [ ]:
errors = abs(y_pred - y_test)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2))
#https://towardsdatascience.com/random-forest-in-python-24d0893d51c0

Mean Absolute Error: 0.67


In [ ]:
print('\n')
# Accuracy on Train
print("The Training Accuracy is: ", knn.score(x_train, y_train))

# Accuracy on Test
print("The Testing Accuracy is: ", knn.score(x_test, y_test))



The Training Accuracy is:  0.5555555555555556
The Testing Accuracy is:  0.4444444444444444


In [ ]:
# Confusion Matrix function
#adopted from https://github.com/Pitsillides91/Python-Tutorials/blob/master/Introduction%20to%20ML%20-%20Logistic%20Regression%20Example/Introduction%20to%20Machine%20Learning%20-%20Logistic%20Regression%20Example%20(Complete).ipynb

def plot_confusion_matrix(cm, classes=None, title='Confusion matrix'):
    """Plots a confusion matrix."""
    if classes is not None:
        sns.heatmap(cm, cmap="YlGnBu", xticklabels=classes, yticklabels=classes, vmin=0, vmax=1, annot=True, annot_kws={'size':50})
    else:
        sns.heatmap(cm, vmin=0, vmax=1)
    plt.title(title)
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

Confusion Matrix

[[4 0 1]
 [2 0 2]
 [0 0 0]]


In [ ]:
y_pred

array([4, 2, 4, 2, 4, 2, 2, 2, 2])

In [ ]:
y_test

39    3
25    2
26    3
43    2
35    2
41    3
4     3
12    2
8     2
Name: Location, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))


Accuracy: 0.44

Micro Precision: 0.44
Micro Recall: 0.44
Micro F1-score: 0.44

Macro Precision: 0.22
Macro Recall: 0.27
Macro F1-score: 0.24

Weighted Precision: 0.37
Weighted Recall: 0.44
Weighted F1-score: 0.40


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# SVM

In [ ]:
#Support Vector Machine
from sklearn.svm import SVC

svm_classifier = SVC(kernel= 'rbf', gamma='auto') #after some research, we chose rbf
svm_classifier.fit(x_train, y_train)
y_predict_svm = svm_classifier.predict(x_test)

In [ ]:
# Use the predict method on the test data
errors = abs(y_predict_svm - y_test)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2))
#https://towardsdatascience.com/random-forest-in-python-24d0893d51c0

Mean Absolute Error: 0.22


In [ ]:
print('\n')
# Accuracy on Train
print("The Training Accuracy is: ", svm_classifier.score(x_train, y_train))

# Accuracy on Test
print("The Testing Accuracy is: ", svm_classifier.score(x_test, y_test))



The Training Accuracy is:  0.8055555555555556
The Testing Accuracy is:  0.8888888888888888


In [ ]:
y_predict_svm

array([3, 2, 3, 2, 2, 3, 3, 2, 4])

In [ ]:
y_pred=y_predict_svm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))


Accuracy: 0.89

Micro Precision: 0.89
Micro Recall: 0.89
Micro F1-score: 0.89

Macro Precision: 0.67
Macro Recall: 0.60
Macro F1-score: 0.63

Weighted Precision: 1.00
Weighted Recall: 0.89
Weighted F1-score: 0.94


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# RF

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

rf_classifier = RandomForestClassifier(max_depth=2, random_state=42)
rf_classifier.fit( x_train, y_train)
y_predict_rf = rf_classifier.predict(x_test)


In [ ]:
errors = abs(y_predict_rf - y_test)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
#https://towardsdatascience.com/random-forest-in-python-24d0893d51c0

Mean Absolute Error: 0.67 degrees.


In [ ]:
print('\n')
# Accuracy on Train
print("The Training Accuracy is: ", rf_classifier.score(x_train, y_train))

# Accuracy on Test
print("The Testing Accuracy is: ", rf_classifier.score(x_test, y_test))




The Training Accuracy is:  0.9722222222222222
The Testing Accuracy is:  0.6666666666666666


In [ ]:
y_pred=y_predict_rf
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))


Accuracy: 0.67

Micro Precision: 0.67
Micro Recall: 0.67
Micro F1-score: 0.67

Macro Precision: 0.67
Macro Recall: 0.47
Macro F1-score: 0.52

Weighted Precision: 1.00
Weighted Recall: 0.67
Weighted F1-score: 0.76


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# DT

In [ ]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier( max_depth=7)
decision_tree = decision_tree.fit(x_train, y_train)
y_predict_dt = decision_tree.predict(x_test)

In [ ]:
errors = abs(y_predict_dt - y_test)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2))
#https://towardsdatascience.com/random-forest-in-python-24d0893d51c0

Mean Absolute Error: 0.33


In [ ]:
print('\n')
# Accuracy on Train
print("The Training Accuracy is: ", decision_tree.score(x_train, y_train))

# Accuracy on Test
print("The Testing Accuracy is: ", decision_tree.score(x_test, y_test))
print('\n')




The Training Accuracy is:  1.0
The Testing Accuracy is:  0.7777777777777778




In [ ]:
y_predict_dt

array([3, 2, 3, 2, 2, 3, 3, 4, 3])

In [ ]:
y_pred=y_predict_dt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))


Accuracy: 0.78

Micro Precision: 0.78
Micro Recall: 0.78
Micro F1-score: 0.78

Macro Precision: 0.60
Macro Recall: 0.53
Macro F1-score: 0.55

Weighted Precision: 0.91
Weighted Recall: 0.78
Weighted F1-score: 0.81


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
data

Eva_1     Evb_1     Evc_1     Eva_2     Evb_2     Evc_2  Location
0   0.080313  0.343100  0.576587  0.000778  0.497417  0.501805         4
1   0.446246  0.037825  0.515929  0.501514  0.000202  0.498285         4
2   0.605344  0.196966  0.197691  0.994117  0.002594  0.003290         4
3   0.983248  0.008130  0.008622  0.605838  0.196892  0.197269         3
4   0.949568  0.006566  0.043865  0.478637  0.120613  0.400750         3
5   0.189513  0.205092  0.605395  0.003696  0.004768  0.991536         4
6   0.181234  0.633001  0.185765  0.183194  0.628601  0.188205         2
7   0.651789  0.052713  0.295499  0.566736  0.093809  0.339456         2
8   0.056972  0.404159  0.538869  0.022908  0.469622  0.507470         2
9   0.191552  0.203290  0.605158  0.003592  0.004467  0.991940         4
10  0.497424  0.488002  0.014574  0.496697  0.498109  0.005194         2
11  0.638575  0.180548  0.180878  0.631501  0.184088  0.184411         2
12  0.486334  0.006801  0.506865  0.497869  0.002227  0.499904         2
13  0.448882  0.489593  0.061525  0.498100  0.501545  0.000355         4
14  0.193417  0.201792  0.604791  0.003516  0.004211  0.992273         4
15  0.180895  0.184452  0.634653  0.181963  0.185770  0.632267         2
16  0.008214  0.984105  0.007681  0.195989  0.606371  0.197640         3
17  0.441515  0.451381  0.107104  0.610691  0.383210  0.006099         4
18  0.196452  0.605914  0.197634  0.003065  0.994331  0.002604         4
19  0.195883  0.605960  0.198157  0.003010  0.994601  0.002389         4
20  0.180070  0.637247  0.182682  0.183610  0.630360  0.186030         2
21  0.003840  0.493117  0.503044  0.039577  0.446623  0.513800         3
22  0.179515  0.180817  0.639667  0.183282  0.184332  0.632386         2
23  0.501547  0.000816  0.497637  0.485216  0.008727  0.506057         3
24  0.632636  0.183226  0.184138  0.630037  0.184385  0.185577         2
25  0.181382  0.630081  0.188537  0.182148  0.626917  0.190935         2
26  0.008980  0.009635  0.981385  0.194473  0.200108  0.605419         3
27  0.496941  0.501723  0.001336  0.493881  0.489524  0.016595         3
28  0.008370  0.983715  0.007915  0.196303  0.606237  0.197460         3
29  0.605440  0.197091  0.197469  0.993986  0.002757  0.003257         4
30  0.983755  0.007781  0.008464  0.605843  0.196716  0.197441         3
31  0.187863  0.341135  0.471003  0.007617  0.920197  0.072186         4
32  0.625453  0.368836  0.005711  0.466081  0.412170  0.121748         3
33  0.321068  0.574490  0.104442  0.352628  0.395131  0.252240         2
34  0.008938  0.009758  0.981304  0.193090  0.201015  0.605895         3
35  0.180719  0.182974  0.636307  0.182931  0.185103  0.631966         2
36  0.605485  0.196989  0.197526  0.994074  0.002664  0.003262         4
37  0.014673  0.894433  0.090894  0.263047  0.341581  0.395372         3
38  0.196144  0.606026  0.197829  0.003027  0.994489  0.002484         4
39  0.008954  0.009952  0.981093  0.191609  0.202174  0.606217         3
40  0.500512  0.168627  0.330860  0.963129  0.004136  0.032735         4
41  0.008113  0.984384  0.007503  0.195739  0.606293  0.197968         3
42  0.983557  0.007927  0.008515  0.605948  0.196758  0.197295         3
43  0.555375  0.417693  0.026932  0.512407  0.412851  0.074742         2
44  0.634837  0.182294  0.182869  0.630541  0.184392  0.185067         2